name: 'project-name' # adjust this to match bq project namespace

config-version: 2
version: '1.0'

# This setting configures which "profile" dbt uses for this project.
# Profiles contain database connection information and should be configured in ~/.dbt/profiles.yml file
profile: 'clickhouse'

# These configurations specify where dbt should look for different types of files.
model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
#analysis-paths: [directorypath]
macro-paths: ['macros']
snapshot-paths: ['snapshots']
#docs-paths: [directorypath]
#asset-paths: [directorypath]

# The target directory is the directory where dbt will store compiled SQL files
target-path: 'target'
log-path: 'logs'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_modules"
  - "dbt_packages"

query-comment: string

#require-dbt-version: version-range | [version-range]

#quoting:
#  database: true | false
#  schema: true | false
#  identifier: true | false

#models:
#  <model-configs>

#seeds:
#  <seed-configs>

#snapshots:
#  <snapshot-configs>

#sources:
#  <source-configs>
  
#tests:
#  <test-configs>

vars:
  surrogate_key_treat_nulls_as_empty_strings: true # turn off legacy behaviour for dbt utils surrogate

#on-run-start: sql-statement | [sql-statement]
#on-run-end: sql-statement | [sql-statement]

#dispatch:
#  - macro_namespace: packagename
#    search_order: [packagename]
