config:
  send_anonymous_usage_stats: false

# big query
#big_query:
#  outputs:
#    dev:
#      dataset: test_dataset_bigquery
#      job_execution_timeout_seconds: 1200
#      job_retries: 1
#      location: EU
#      method: oauth
#      priority: interactive
#      project: bq-test-project
#      threads: 8
#      type: bigquery
#  target: dev

# clickhouse 
clickhouse_profile:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: [default] #Clickhouse database for dbt models, using default is not recommended
      retries: 1
      connect_timeout: 1200
