apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
data:
  CLICKHOUSE_USER: ZGVmYXVsdA==
  CLICKHOUSE_DB: ZGVmYXVsdA==
  #CLICKHOUSE_PASSWORD: b3U3OUg1LTAxaEd6UC1iT2dxOA==
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: MQ==