namespace: dev

# clickhouse deployment configuration
clickhouse:
  deployment:
    name: clickhouse
    # replicas is the number of pods to create
    replicas: 1
    strategy:
      type: RollingUpdate
      maxSurge: 3
    image: 
      # repository is the name of the repository on dockerhub
      repository: slowsunday/fulljoin-clickhouse
      # tag is used to tag the repository, in this case latest version of repository is userd
      tag: latest
    # ports represents default ports for clickhouse server, http:8123, tcp:9000;9009  
    ports:
      port1: 8123
      port2: 9000
      port3: 9009
    secret: clickhouse-secret

  # configmap configuration
  configmap:
    enabled: true
    name: clickhouse-config
    # svcHost is a hostname of the server, on minikube defaults to 127.0.0.1
    svcHost: host.minikube.internal
    # port is the port number attached to the svcHost, the above would be equal to http://127.0.0.1:8123
    port: "8123"

  # Service configuration
  service:
    type: ClusterIP
    ports:
      http:
        name: http
        port: 8123
        targetPort: 8123
      tcp:
        name: tcp
        port: 9000
        targetPort: 9000