clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: clickhouse
      port: "{{ env_var('CLICKHOUSE_SERVICE_PORT') | int }}"
      user: admin
      password: ''
      secure: False