apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbt
spec:
  serviceName: "not-applicable"
  selector:
    matchLabels:
      app: dbt
  template:
    metadata:
      labels:
        app: dbt
    spec:
      containers:
        - name: dbt
          image: slowsunday/fulljoin:latest
          envFrom:
            - configMapRef:
                name: dbt-configmap
            - secretRef:
                name: dbt-secret
          volumeMounts:
            - mountPath: "/dbt"
              name: dbt-volume
      volumes:
        - name: dbt-volume
          persistentVolumeClaim:
            claimName: dbt-pvc