{{- if .Values.dbt.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dbt.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dbt.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io.managed-by: {{ .Release.Service }}
  namespace: {{ .Values.namespace }}
data:
  CLICKHOUSE_SERVICE_ADDRESS: "{{ .Values.dbt.configmap.svcHost }}"
{{- end -}}